kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    run: jupyterhub
  name: jupyterhub
  namespace: default
  resourceVersion: "426209"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/jupyterhub
  uid: 1fa35062-1ec5-11e7-a4d6-000d3a254011
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jupyterhub
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: jupyterhub
    spec:
      containers:
      - image: jupyterhub:withRv1
        imagePullPolicy: IfNotPresent
        name: jupyterhub
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: gluster-vc
            mountPath: /home/
        volumes:
          - name: pvc-63d99004-1c92-11e7-a4d6-000d3a254011
