apiVersion: v1
kind: Pod
metadata:
  name: jupyterhub-withr
  namespace: jupyterhub
  labels:
    name: jupyterhub-withr
spec:
  containers:
  - name: jupyterhub-withr
    image:  l2cconseils/jupyterhub:latest
    ports:
    - name: web
      containerPort: 8000
    volumeMounts:
    - name: gluster-jpt-vol
      mountPath: /home
  volumes:
  - name: gluster-jpt-vol
    persistentVolumeClaim:
      claimName: gluster-jpt
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-web
  namespace: jupyterhub
spec:      
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30300
  selector:
    app: jupyterhub-withr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gluster-jpt
 namespace : jupyterhub
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-dyn
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 5Gi
