kind: Service
apiVersion: v1
metadata:
    run: jupyterhubwithr
    name: ui-jupyterhubwithr
spec:
  selector:
    app: jupyterhubwithr
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 30100
