apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gluster-jpt
 namespace : jupyterhub
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-dyn
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
    storage: 5Gi
