# Prerequisites : Heketi + glusterFS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gluster-dyn
provisioner: kubernetes.io/glusterfs
parameters:
  restauthenabled: "false"
  resturl: http://10.244.2.4:8080
